apiVersion: v1
kind: Service
metadata:
  name: petq-apiserver
  labels:
    app: petq-apiserver
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30100
      protocol: TCP
  selector:
    app: petq-apiserver


